




 20%|████████████████████████▌                                                                                                  | 4/20 [14:53<59:25, 222.82s/it]



 35%|███████████████████████████████████████████                                                                                | 7/20 [26:01<48:16, 222.78s/it]





 60%|█████████████████████████████████████████████████████████████████████████▏                                                | 12/20 [44:38<29:46, 223.36s/it]




 80%|█████████████████████████████████████████████████████████████████████████████████████████████████▌                        | 16/20 [59:32<14:55, 223.98s/it]



100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [1:14:23<00:00, 222.97s/it] stage3_gather_16bit_weights_on_model_save=false. Saving the full checkpoint instead, use zero_to_fp32.py to recover weights
Saving model checkpoint to /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20
{'loss': 1.1209, 'grad_norm': 1.3161758184432983, 'learning_rate': 0.0, 'epoch': 9.28}
/home/piaoxx/miniconda3/envs/env/lib/python3.10/site-packages/peft/utils/other.py:619: UserWarning: Unable to fetch remote file due to the following error (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /Qwen/Qwen2-7B-Instruct/resolve/main/config.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f82f41f2890>: Failed to resolve \'huggingface.co\' ([Errno -3] Temporary failure in name resolution)"))'), '(Request ID: 42a4ba4b-4d58-4f38-a4fa-434d867a5bbd)') - silently ignoring the lookup for the file config.json in Qwen/Qwen2-7B-Instruct.
  warnings.warn(
/home/piaoxx/miniconda3/envs/env/lib/python3.10/site-packages/peft/utils/save_and_load.py:218: UserWarning: Could not find a config file in Qwen/Qwen2-7B-Instruct - will assume that the vocabulary was not modified.
  warnings.warn(
[2024-09-07 20:04:56,733] [INFO] [logging.py:96:log_dist] [Rank 0] [Torch] Checkpoint global_step20 is about to be saved!
[2024-09-07 20:04:56,751] [INFO] [logging.py:96:log_dist] [Rank 0] Saving model checkpoint: /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_model_states.pt
[2024-09-07 20:04:56,751] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_model_states.pt...
[2024-09-07 20:05:04,575] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_model_states.pt.
[2024-09-07 20:05:04,658] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_optim_states.pt...
[2024-09-07 20:05:05,175] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_optim_states.pt.
[2024-09-07 20:05:05,176] [INFO] [engine.py:3536:_save_zero_checkpoint] zero checkpoint saved /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_optim_states.pt
[2024-09-07 20:05:05,251] [INFO] [torch_checkpoint_engine.py:33:commit] [Torch] Checkpoint global_step20 is ready now!
[2024-09-07 20:05:05,298] [INFO] [logging.py:96:log_dist] [Rank 0] [Torch] Checkpoint global_step20 is about to be saved!
[2024-09-07 20:05:05,311] [INFO] [logging.py:96:log_dist] [Rank 0] Saving model checkpoint: /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_model_states.pt
[2024-09-07 20:05:05,311] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_model_states.pt...
Repo card metadata block was not found. Setting CardData to empty.
09/07/2024 20:05:06 - WARNING - huggingface_hub.repocard -   Repo card metadata block was not found. Setting CardData to empty.
[2024-09-07 20:05:06,267] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_model_states.pt.
[2024-09-07 20:05:06,339] [INFO] [torch_checkpoint_engine.py:21:save] [Torch] Saving /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_optim_states.pt...
[2024-09-07 20:05:06,366] [INFO] [torch_checkpoint_engine.py:23:save] [Torch] Saved /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_optim_states.pt.
[2024-09-07 20:05:06,367] [INFO] [engine.py:3536:_save_zero_checkpoint] zero checkpoint saved /home/piaoxx/piao1/Domain_LLM/checkpoint/domain-csc-20240907184749/checkpoint-20/global_step20/zero_pp_rank_0_mp_rank_00_optim_states.pt
[2024-09-07 20:05:06,440] [INFO] [torch_checkpoint_engine.py:33:commit] [Torch] Checkpoint global_step20 is ready now!
/home/piaoxx/miniconda3/envs/env/lib/python3.10/site-packages/peft/utils/other.py:619: UserWarning: Unable to fetch remote file due to the following error (MaxRetryError('HTTPSConnectionPool(host=\'huggingface.co\', port=443): Max retries exceeded with url: /Qwen/Qwen2-7B-Instruct/resolve/main/config.json (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f82fd5001c0>: Failed to resolve \'huggingface.co\' ([Errno -3] Temporary failure in name resolution)"))'), '(Request ID: 3577ef6e-c1dc-46c7-9b44-76a539666d22)') - silently ignoring the lookup for the file config.json in Qwen/Qwen2-7B-Instruct.
  warnings.warn(
/home/piaoxx/miniconda3/envs/env/lib/python3.10/site-packages/peft/utils/save_and_load.py:218: UserWarning: Could not find a config file in Qwen/Qwen2-7B-Instruct - will assume that the vocabulary was not modified.
  warnings.warn(
Training completed. Do not forget to share your model on huggingface.co/models =)
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 20/20 [1:15:14<00:00, 225.73s/it]
{'train_runtime': 4535.0619, 'train_samples_per_second': 0.602, 'train_steps_per_second': 0.004, 'train_loss': 1.3278314590454101, 'epoch': 9.28}